CREATE OR REPLACE VIEW SCHOOL_SUBSET (School_name, safety_Rating,
 Family_Rating, Environment_Rating, Instruction_Rating, Leaders_Rating, Teachers_Rating)
 as SELECT NAME_OF_SCHOOL, SAFETY_ICON, FAMILY_INVOLVEMENT_ICON, ENVIRONMENT_ICON, INSTRUCTION_ICON,
 LEADERS_ICON, TEACHERS_ICON
 FROM SCHOOLS;
 
SELECT* FROM SCHOOL_SUBSET;
SELECT School_Name,Leaders_Rating 
FROM SCHOOL_SUBSET; 