SELECT S.CASE_NUMBER, S.PRIMARY_TYPE, C.COMMUNITY_AREA_NAME 
FROM CHICAGO_CRIME_DATA AS S 
LEFT JOIN CENSUS_DATA AS C 
ON S.COMMUNITY_AREA_NUMBER = C.COMMUNITY_AREA_NUMBER
WHERE S.LOCATION_DESCRIPTION LIKE '%SCH%'